### ISSUE TITLE
Integrating with mainstream tools

### ISSUE THREAD

**Issue by karol-majewski** [acrazing/dpdm#11]
Hello and thank you for your work. It's impressive how fast and straightforward `dpdm` is compared to other tools that aim to solve the same problem.

So far, I've used [`tslint-no-circular-imports`](https://www.npmjs.com/package/tslint-no-circular-imports) and [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import) with the `no-cycle` option enabled. They are way slower (especially the ESLint one), but one thing can be said about them: they integrate nicely with the ecosystem in which they are used. Using a lint rule is easy when you already have a linter in place, and can be extra powerful if the rule provides useful feedback right in your IDE of choice.

My question is: what are your recommendations for using `dpdm`?

- In your opinion, what is the best way for teams to integrate it into their workflow?
- Do you have any plans to turn it into an ESLint plugin, or is it a bad idea?
- Would it be possible to create a Visual Studio Code extension that utilizes `dpdm` and warns about circular dependencies during development?

Thank you again, and keep up the good work 🙇

**Comment by acrazing** [comment]
Well, in my opinion, `circular dependencies` is a rare case, and detecting it is also a very time-consuming task, so I think it should be tested in the CI/CD system.

**Comment by acrazing** [comment]
You can find some practical ways to use it [here](https://github.com/acrazing/dpdm/network/dependents?package_id=UGFja2FnZS0xNDEyNjQzOA%3D%3D).

**Comment by karol-majewski** [comment]
Thanks. That's what I ended up doing.
