### ISSUE TITLE
Default exclusion settings are not respected on Windows

### ISSUE THREAD

**Issue by karol-majewski** [acrazing/dpdm#12]
Hello and thank you for your work.

As recommended in #11, I decided to use `dpdm` in my CI pipeline. The remote build agent is using Windows, and that's where the issue manifests.

It seems like on Windows, the default value for the `--exclude` parameter (`"\/node_modules\/"`) is not respected, and the tool finds circular dependencies in third-party code. That very same command works just fine when executed on macOS, skipping `node_modules` as expected.

Please let me know if any extra information is required to resolve this.

**Comment by acrazing** [comment]
The default value of `--exclude` is `/\/node_modules\//` which only works on Unix like system, I will fix it ASAP. As a temporary solution, you can explicitly set the `--exclude` parameter as `node_modules` when using `dpdm` in command line. For example:

```bash
dpdm --exclude node_modules .
```
