### ISSUE TITLE
Always got `Unknown argument: ENTRY_FILE_PATH` error

### ISSUE THREAD

**Issue by treelite** [acrazing/dpdm#14]
Hey there :) I just updated the `dpdm` to the latest version and always got this error `Unknown argument: ENTRY_FILE_PATH` when I ran something like "dpdm ENTRY_FILE_PATH". 

Looks like it's related to the yargs upgrade(https://github.com/yargs/yargs/pull/1977) that the `strict()` will throw error if there is any unknown argument. maybe the `strictOptions()` become a better choice now?

**Comment by acrazing** [comment]
Can you show the complete command you executed? I can't seem to reproduce this problem:

![image](https://user-images.githubusercontent.com/10029810/128300743-54529cb1-66c1-4e4d-9d49-4b9d88d5d7c4.png)

**Comment by acrazing** [comment]
According to #15 , it is fixed in `dpdm@3.7.1`, you can try it in the latest version now, thanks.
