### ISSUE TITLE
Can you please explain what "lose .. from .." means?

### ISSUE THREAD

**Issue by demian85** [acrazing/dpdm#2]
I'm getting a lot of warnings and one of them is:
`lose "client/components/admin/configurations/columns" from "src/client/store/reducers/page-grid.ts"` 

I'm not really sure what to do in that case. Can you please give me a few details?

Thanks.

**Comment by acrazing** [comment]
I'm sorry for my poor English, it means cannot resolve `client/components/admin/configurations/columns` from `src/client/store/reducers/page-grid.ts`.
