### ISSUE TITLE
ignore dynamic imports when searching for circular deps

### ISSUE THREAD

**Issue by jaroslaw-weber** [acrazing/dpdm#23]
currently dpdm is detecting dynamic imports as an issue but that's not always the case.
can we set it so dynamic imports & require are ignored?

**Comment by theo-walton** [comment]
this feature would be very useful as we disallow circular dependencies for my project, with exceptions being made for dynamic imports. The lack of this flag means this can't be used in CI

**Comment by acrazing** [comment]
This feature is added in v3.13.0, you can try it now:

1. Get the latest version:

    ```bash
    npm i -g dpdm@latest
    dpdm --version # make sure it is 3.13.0
    ```

2. Add flag `--skip-dynamic-imports circular` to ignore dynamic imports when parse circular dependencies:

    ```bash
    dpdm --skip-dynamic-imports circular index.js
    ```

3. Or you can set the value of `--skip-dynamic-imports` as `tree` to ignore dynamic imports when parse dependencies:

    ```bash
    dpdm --skip-dynamic-imports tree index.js
    ```
