### ISSUE TITLE
Unused files are incorrect

### ISSUE THREAD

**Issue by ciriousjoker** [acrazing/dpdm#27]
I have an `index.ts` that is the main entry point from which I export all Firebase cloud functions.

However, files still appear as "unused" even though I'm directly exporting them from this file.

Anything I can do here?

**Comment by acrazing** [comment]
Could you paste the command you ran with `dpdm`?

**Comment by ciriousjoker** [comment]
Tried to reproduce it with this command:
`npx dpdm ./dist/apps/backend/src/functions/someFile.js --detect-unused-files-from ./dist/apps/backend/**/*.ts >> output.log`

**I get back this:**
```log
• Unused files
0) dist/apps/backend/libs/shared/src/index.d.ts
```

Perhaps I was using a different command when I opened this or I didn't see the ".d.ts". Either way, this doesn't affect our production code, so this can be closed.

**Comment by acrazing** [comment]
Does your directory has the file named as `dist/apps/backend/libs/shared/src/index.js`? If true, the `dist/apps/backend/libs/shared/src/index.d.ts` will not be tracked in dependency tree, which means unused.

**Comment by ciriousjoker** [comment]
Yes, thanks for the explanation!
