### ISSUE TITLE
Warnings don't ignore non-root node_modules

### ISSUE THREAD

**Issue by ciriousjoker** [acrazing/dpdm#28]
Paths:

```log
...
11) skip "dist/apps/project/node_modules/jwt-decode/build/jwt-decode.esm.js"
...
````

I've tried ` --exclude ".*node_modules.*"`, but it doesn't change anything.

**Comment by acrazing** [comment]
The ignored modules are printed in `Warnings` as `skip ...`, it works as expected.

- If you want to hide `Warnings` in output, you can add `--no-warning` flag when you run dpdm.
- If you want to exclude root node_modules exactly, you can use a more precise `--exclude` flag, eg: `--exclude "$PWD/node_modules"`.
