### ISSUE TITLE
Ignore import type

### ISSUE THREAD

**Issue by fysntian** [acrazing/dpdm#29]
Typescript allows "import type" for just a type require, and it will be ignored in complied .js file. My codes is here:

// file /contexts/task-request-context.ts:
import type Task from '../models/task.model';

// file /models/task.model.ts
import TaskRequestContext from '../contexts/task-request-context';

And I think they won't be Circular Dependencies.

**Comment by andrejpavlovic** [comment]
https://github.com/acrazing/dpdm/blob/579a35f03144f1f0e878746f41e4ab0bb8e363db/README.md?plain=1#L73-L77

**Comment by acrazing** [comment]
@andrejpavlovic You are awesome.

@fysntian You can add the flag `-T` to ignore type references when you run dpdm.

TypeScript hides many internal APIs, includes the method to detect a value import is type reference or value reference. So dpdm drops the type references by transform TypeScript file to JavaScript file violently. It will drop both type imports and value imports only reference types.
