### ISSUE TITLE
Support TypeScript v5

### ISSUE THREAD

**Issue by ysgk** [acrazing/dpdm#30]
Because dpdm currently depends on typescript@^4.9.4, using the latest version of typescript and dpdm together will result in two different typescript versions being installed. This is quite an overhead in terms of the installation size, and it would be nice if dpdm would support typescript v5.

**Comment by acrazing** [comment]
TypeScript is upgraded to 5.0.2!

You can try it by install the latest version of dpdm:

```bash
npm i -g dpdm@latest
dpdm --version # make sure it is 3.13.0
```

**Comment by ysgk** [comment]
Confirmed, thank you.
