### ISSUE TITLE
apply tree shaking to dependency tree

### ISSUE THREAD

**Issue by andrejpavlovic** [acrazing/dpdm#31]
I've been looking for a tool that would be able to recursively extract all the dependencies given a single typescript file as an entry point. After looking around, I came back to `dpdm`, since I remembered that it must be able to generate a dependency tree in order to determine circular dependencies. I wasn't disappointed - `parseDependencyTree` does a really good job!

However, I would like to apply tree shaking after getting the tree and currently the tree doesn't contain any information about what each file imports/exports.

Would it make sense to record list of imports and exports in `Dependency` type as the tree is generated, and then use these in a subsequent step to shake the tree? By shaking the tree I mean, removing dependencies that are not directly imported (like unused modules that are re-exported in barrel files).

current:
https://github.com/acrazing/dpdm/blob/5dd1d67a8bdd4a8c91a63b368195c1e5ea547ac0/src/types.ts#L20-L25
proposed:
```typescript
 export interface Dependency { 
   issuer: string; 
   request: string; 
   kind: DependencyKind;
   id: string | null; // filename or shorten filename, cannot resolve will be null 
   imports: string[];
   exports: string[];
 } 
```

Maybe there is already some other tool out there that does this, but so far `parseDependencyTree` is the closest I've found.

**Comment by acrazing** [comment]
I think this is a bit out of scope. `dpdm` is currently only intended to be used to analyze dependencies. I think you need to look for other tools. If that doesn't work, you can try manually modifying `dpdm` in your `node_modules`, and then use a tool like `patch-package` to manage your changes.
