### ISSUE TITLE
@types/* should be devDependencies

### ISSUE THREAD

**Issue by carmanchris31** [acrazing/dpdm#32]
https://github.com/acrazing/dpdm/blob/5dd1d67a8bdd4a8c91a63b368195c1e5ea547ac0/package.json#L63-L65

`@types/fs-extra` and `@types/yargs` are currently listed as dependencies even though they are not relevant once dpdm is compiled/shipped.

This creates conflicts for downstream projects that use a different version of `@types/fs-extra` or `@types/yargs`

**Comment by acrazing** [comment]
It's fixed now. You can avoid this issue by installing the latest version (`>= 3.13.1`) of `dpdm`.
