### ISSUE TITLE
Don't output red "circular dependencies" text when there are no circular dependencies

### ISSUE THREAD

**Issue by robinsonrc** [acrazing/dpdm#36]
Regarding the following code, which always appears when checking circular dependencies:

`chalk.bold.red('• Circular Dependencies')`

When scanning the output of DPDM, which I often run as part of a bigger collection of scripts/checks, seeing red text immediately makes me think there's a problem. This red text appears whether there are or are not circular dependencies.

I'd personally prefer no red text to be displayed (perhaps don't display this text at all) when there are no circular dependencies.

Happy to submit a PR if this is something you'd consider (but would need to know what your preferred option would be if so).

Thanks.

**Comment by acrazing** [comment]
OK, I have changed the color to green if there is no cycles.

**Comment by robinsonrc** [comment]
Sounds great, thank you!
