### ISSUE TITLE
[BUG] No appropriate feedback when the file passed to the command line isn't found

### ISSUE THREAD

**Issue by kylefiegener-gardiant** [acrazing/dpdm#38]
**Describe the bug**
Invoking `dpdm` on the command line with a file that doesn't exist produces the following *very strange*, but nonetheless misleadingly-positive output:
```
√ [0/0] Analyze done!
• Dependencies Tree


• Circular Dependencies
  ✅ Congratulations, no circular dependency was found in your project.

• Warnings

```
Importantly, you are not informed that the file was not found (or that there is even a problem at all).

**To Reproduce**
1. Enter `dpdm ./this_file_does_not_exist_well_probably_I_mean_it_would_be_an_amazing_and_bizarre_coincidence.js` on the command line
1. Press Enter

**Expected behavior**
The command line process aborts with an informative message when it does not find any file(s) to process.

**Additional context**
Windows 11

**Comment by acrazing** [comment]
Good point, I will fix it now.

**Comment by acrazing** [comment]
It checks now (from cli only).
