### ISSUE TITLE
[Feature] optimize concurrent runs via cache

### ISSUE THREAD

**Issue by soryy708** [acrazing/dpdm#41]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I'd like to be able to efficiently run dpdm on multiple entrypoints concurrently.

**Describe alternatives you've considered**

I can provide a very large array of entrypoints, but analyzing things afterwards will be complicated.

**Additional context**

If dpdm would have cached parts of the dependency graph, it wouldn't have needed to re-construct parts of it in case of concurrent runs.

For example:

```typescript
const [circulars1, circulars2] = await Promise.all([
  dpdm.parseCircular(await dpdm.parseDependencyTree(ep1, {
    context: cwd,
  })),
  dpdm.parseCircular(await dpdm.parseDependencyTree(ep2, {
    context: cwd,
  })),
])
```

If there's some overlap between `ep1` and `ep2`'s dependencies, we're doing unnecessary work, because we could have cached the first time.

**Comment by acrazing** [comment]
Or you can write a detect function to check if `ep1` is in a cycle or not. It is faster than find all cycles.
