### ISSUE TITLE
[BUG] false-negative in parseCircular

### ISSUE THREAD

**Issue by soryy708** [acrazing/dpdm#43]
**Describe the bug**

`parseCircular` incorrectly misses some of the circular dependencies in the `tree` given it.

**To Reproduce**

Run the tests introduced by:

- https://github.com/acrazing/dpdm/pull/42

Specifically:

```typescript
const tree = {
  start: [dependencyFactory('left1'), dependencyFactory('right1')],
  left1: [dependencyFactory('left2')],
  left2: [dependencyFactory('intersection')],
  right1: [dependencyFactory('intersection')],
  intersection: [dependencyFactory('start')],
};

let actual: Array<string[]>;
beforeAll(() => {
  actual = parseCircular(tree);
});

it('Should count two cycles', () => {
  expect(actual.length).toBe(2);
});

it('Should include the ids involved in the cycle', () => {
  expect(actual[0]).toMatchObject([
    'start',
    'left1',
    'left2',
    'intersection',
  ]);
  expect(actual[1]).toMatchObject(['start', 'right1', 'intersection']);
});

function dependencyFactory(id: string): Dependency {
  return {
    issuer: '',
    request: '',
    kind: DependencyKind.StaticImport,
    id,
  };
}
```

**Expected behavior**

All tests should pass.

If we look at the dependency graph in the screenshots section, we expect to see 2 cycles:

`[['start', 'left1', 'left2', 'intersection'], ['start', 'right1', 'intersection']]`

**Actual behavior**

Some of the tests fail.

It correctly includes `['start', 'left1', 'left2', 'intersection']`, but it incorrectly doesn't include `['start', 'right1', 'intersection']`.

**Screenshots**

![image](https://github.com/acrazing/dpdm/assets/2157782/26f631fb-2375-4536-a973-a7341c3bdc1e)

**Additional context**

Looks like it's related to

**Comment by acrazing** [comment]
This is intentional, for performance.

Because I found find all the cycles in a directed graph is expensive. So I deleted the visited node permanently. The side effect is that it is impossible to find cycles with overlapping edges. Just like the example you gave.

I'm not familiar with graph theory, maybe there is a better solution. We can discuss it here.

**Comment by acrazing** [comment]
Can you try changing the algorithm to Tarjan's SCC and compare with the existing algorithm?
