### ISSUE TITLE
[Feature] Specify a directory and search for circular dependencies in it (dpdm)

### ISSUE THREAD

**Issue by gearonix** [acrazing/dpdm#45]
**Describe the solution you'd like**

It would also be nice to be able to specify a directory and search for circular dependencies in it.

Perhaps it would look something like this

```sh
dpdm --no-warning \
     --no-tree \
     --directory ./src
```

The root file `index.ts` is not always available

 Maybe we can implement the functionality using [node-glob](https://github.com/isaacs/node-glob) or something like that.

**Comment by acrazing** [comment]
It supports glob already. You can use it like this:

```bash
dpdm --no-warning \
     --no-tree \
     --directory './src/*.*'
```
