### ISSUE TITLE
Import mapping

### ISSUE THREAD

**Issue by ddurschlag** [acrazing/dpdm#49]
We have some ES6 modules which import eachother by package name. In other words package Foo has a.js and b.js, and b.js imports from "Foo/a". It seems dpdm doesn't understand this. It'd be good to have some way to say "Foo points at the current directory" or similar, maybe something like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap

**Comment by acrazing** [comment]
Can you show me your code about importing in your `a.js` and `b.js`?

**Comment by ddurschlag** [comment]
I cannot; it is proprietary. If you have questions about it I'd be happy to answer them, however.

**Comment by acrazing** [comment]
I guess TypeScript Path Mapping is what you wanted? You can get more detailed information here: https://github.com/acrazing/dpdm/issues/50#issuecomment-1984885777.

**Comment by ddurschlag** [comment]
This should work; I'll try soon. Thank you!
