### ISSUE TITLE
Support for full path import resolution of re-exports

### ISSUE THREAD

**Issue by awilson9** [acrazing/dpdm#56]
Wondering if the following is currently supported, and if not then perhaps you could treat it as a feature request.

Currently, parsing the dependency tree stops when it reaches the shortest path export. Is there a way to configure dpdm to continue down the import chain in the case that that path is just a re-export of an import?

For example, 

`c.ts`

```
export const foo = {};
```

`b.ts`

```
export * from './c'
```

`a.ts`
```
import { foo } from './b`
```

in this case the dependency graph would resolve to `./c.ts` instead of `./b.ts`

**Comment by acrazing** [comment]
Our of scope.

What we wanted is to analysis the real dependency graph. But what you want defeats the purpose.
