### ISSUE TITLE
[BUG] Don't report circular dependencies for self-export/self-import

### ISSUE THREAD

**Issue by OliverJAsh** [acrazing/dpdm#57]
**Describe the bug**

Self-exports are counted as circular dependencies.

**To Reproduce**

`a.ts`:
```ts
export * as A from './a';
```

Here's an article about why this pattern is useful: https://medium.com/unsplash/named-namespace-imports-7345212bbffb

**Expected behavior**

No errors.

**Comment by acrazing** [comment]
Why would you need to do this? It's a bad design:

If the content of the file is:

```ts
export const a = 1;
export * as A from './a';
```

What the value of following expression should be?

```ts
import { A } from './a';
console.log(A.A.A.A.A);
```

According to the ES mechanism, this writing method is acceptable. It is essentially a circular reference.

**Comment by OliverJAsh** [comment]
Here's an article about why this pattern is useful: https://medium.com/unsplash/named-namespace-imports-7345212bbffb

**Comment by acrazing** [comment]
I have already read that. But I don't agree with that solution. It makes the type system a mess.
