### ISSUE TITLE
[Feature] refactoring with Rust

### ISSUE THREAD

**Issue by GrinZero** [acrazing/dpdm#59]
**Is your feature request related to a problem? Please describe.**

When the project is large and the dependencies are complex, the analysis time of `dpdm` can reach the minute level. Can the current `dpdm` project be rustized to improve efficiency in order to enhance performance.

**Describe the solution you'd like**

Implementing a 100% compatible new version of dpdm using Rust

**Describe alternatives you've considered**

- https://github.com/rust-redo/import-tree: Lack of maintenance

**Comment by acrazing** [comment]
No need to merge, keep your project independent.
