### ISSUE TITLE
Terminating with exit code 1 if any circular dependencies are found

### ISSUE THREAD

**Issue by karlpetersson** [acrazing/dpdm#8]
When integrating dpdm with CI, it would be nice if the cli tool would terminate with exit code 1 if any circular dependencies are found. Or, if it at least provided a flag to enable this behaviour.

What are your thoughts on this? Would gladly submit a PR if you are accepting contributions.

**Comment by EvanLovely** [comment]
This script works for me. I run it and output the data to json, which contains a `circulars` array. I find the length of that array and then use that as the exit code: 0 circular dependencies means a 0 exit code (i.e. won't fail CI)

```bash
#!/bin/bash
npx dpdm ./src/index.tsx --circular --transform --output dpdm-results.json
CIRCULARS=`node --print --eval 'require("./dpdm-results.json").circulars.length'`
echo "$CIRCULARS total circular dependencies detected"
rm dpdm-results.json
exit $CIRCULARS
```

**Comment by acrazing** [comment]
Well, option `--exit-code` is introduced in version `3.5.0`, you can try it by install the latest version now.

Install:

```bash
yarn global add dpdm@latest
```

Usage:

```bash
dpdm -T --exit-code circular:1 ./src/index.tsx

echo $? # => should be 1 if circular dependency exits
```

If you specify `--exit-code` as `circular:1`, the program will exit with code `1` if your project has circular dependency.
