### ISSUE TITLE
What does 'dpdm' stands for?

### ISSUE THREAD

**Issue by beenotung** [acrazing/dpdm#9]
I suppose 'dp' in 'dpdm' stands for dependency. What about the 'dm'?

Does it stand for dependency detective manager?
Or dependency data model?

**Comment by acrazing** [comment]
Maybe (d)e(p)en(d)ency (m)anager? I don't know, I'm sorry I forgot.

**Comment by beenotung** [comment]
That helps me remembering the package (cli) name :+1:
